# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]
port:             9001

# Custom vars
current_version:  3.0.0
repo:             https://github.com/izer0x/bootstrap-3-arabic
download:         https://github.com/izer0x/bootstrap-3-arabic/archive/master.zip
download_dist:    https://github.com/izer0x/bootstrap-3-arabic/archive/master.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js
